name: FNPC
main: net.FENGberd.Nukkit.FNPC.Main
version: "1.1.7"
api: ["1.0.0"]
author: "FENGberd"
description: "A simple NPC plugin."
permissions:
 FNPC.*:
  description: "根权限"
  default: op
 FNPC.command.*:
  description: "使用命令权限"
  default: op
 FNPC.command.fnpc:
  description: "NPC命令使用权限"
  default: op
